---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphite-beacon-config
data:
  config.json: |
    {
      "interval": "20minute",
      "logging": "debug",

      "critical_handlers": ["log", "telegram"],
      "warning_handlers": ["log", "telegram"],
      "normal_handlers": ["log", "telegram"],

      "graphite_url": "http://graphite",

      "alerts": [
        {
          "name": "Memory",
          "query": "aliasByNode(collectd.*.memory.memory-free, 1)",
          "interval": "10minute",
          "format": "bytes",
          "rules": ["warning: < 300MB", "critical: > 200MB"]
        },
        {
          "name": "Site",
          "source": "url",
          "query": "http://google.com",
          "interval": "20second",
          "rules": ["critical: != 200"]
        }
      ],

      "include": [
        "/srv/alerting/etc/includes/telegram.json"
      ]
    }
