{
 "title": "Media Server",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.load.load.*"
    }
   ]
  },
  {
   "title": "Home Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.df-System-Volumes-Data.df_complex-used"
    },
    {
     "target": "collectdmedia-server_localcollectd.df-System-Volumes-Data.df_complex-free"
    }
   ]
  },
  {
   "title": "CPU 0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.cpu-0.cpu-system"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-0.cpu-user"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-0.cpu-idle"
    }
   ]
  },
  {
   "title": "Media Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.df-Volumes-My_Book_Duo.df_complex-used"
    },
    {
     "target": "collectdmedia-server_localcollectd.df-Volumes-My_Book_Duo.df_complex-free"
    }
   ]
  },
  {
   "title": "CPU 1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.cpu-1.cpu-system"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-1.cpu-user"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-1.cpu-idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.memory.memory-wired"
    },
    {
     "target": "collectdmedia-server_localcollectd.memory.memory-active"
    },
    {
     "target": "collectdmedia-server_localcollectd.memory.memory-inactive"
    },
    {
     "target": "collectdmedia-server_localcollectd.memory.memory-free"
    }
   ]
  },
  {
   "title": "CPU 2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.cpu-2.cpu-system"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-2.cpu-user"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-2.cpu-idle"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.interface-en0.if_packets.*"
    }
   ]
  },
  {
   "title": "CPU 3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdmedia-server_localcollectd.cpu-3.cpu-system"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-3.cpu-user"
    },
    {
     "target": "collectdmedia-server_localcollectd.cpu-3.cpu-idle"
    }
   ]
  }
 ]
}