# vim:ft=ansible
---
- hosts: kube_controllers
  become: yes
  tasks:
    - name: install NFS server
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: create NFS directory
      file:
        path: /mnt/nfs
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: add line to /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: ^/dev/sda1
        firstmatch: yes
        line: /dev/sda1     /mnt/nfs  ext4  defaults  0   0
        insertafter: EOF

    - name: mount drive
      mount:
        path: /mnt/nfs
        src: /dev/sda1
        fstype: ext4
        state: mounted

    - name: add line to /etc/exports
      lineinfile:
        path: /etc/exports
        regexp: ^/mnt/nfs
        firstmatch: yes
        line: /mnt/nfs        192.168.1.0/24(rw,sync,no_subtree_check) localhost(rw,sync,no_subtree_check) 10.244.0.0/24(rw,sync,no_subtree_check)
        insertafter: EOF

    - name: run exportfs
      command: exportfs -a

    - name: restart nfs
      systemd:
        name: nfs-kernel-server
        state: restarted

- hosts: kube_workers
  become: yes
  tasks:
    - name: install NFS common
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: check if mount point exists
      stat:
        path: /mnt/nfs
      register: nfs_mount

    - name: create mount point if it doesn't exist
      file:
        path: /mnt/nfs
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777
      when: nfs_mount.stat.isdir is not defined or not nfs_mount.stat.isdir

    - name: mount NFS volume
      mount:
        path: /mnt/nfs
        src: k8s-controller01.local:/mnt/nfs
        state: mounted
        fstype: nfs
