# vim:ft=ansible
---
- hosts: kube_controllers
  tasks:
    - name: Initialize the cluster
      become: yes
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init_output

    - name: Create the ~/.kube directory
      file:
        path: $HOME/.kube
        state: directory

    - name: Get the user ID
      set_fact:
        user_id: "{{ ansible_facts.user_id }}"

    - name: Copy the admin.conf to ~/.kube
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ user_id }}/.kube/config"
        remote_src: yes
        owner: "{{ user_id }}"
        group: "{{ user_id }}"

    - name: Install pod network
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/v0.13.0/Documentation/kube-flannel.yml
      when: kubeadm_init_output.changed

    - name: Get Token CA hash
      shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"
      register: token_ca_hash

    - name: Get token value
      shell: kubeadm token list | grep "The default bootstrap token generated by 'kubeadm init'." | awk '{print $1}'
      register: token_value

    - name: Get join command
      set_fact:
        join_command: "kubeadm join {{ ansible_wlan0.ipv4.address }}:6443 --token {{ token_value.stdout_lines[0] }} --discovery-token-ca-cert-hash sha256:{{ token_ca_hash.stdout_lines[0] }}"

- hosts: kube_workers
  become: yes
  tasks:
    - name: Join cluster
      command: "{{ hostvars[groups.kube_controllers[0]].join_command }}"
      args:
        creates: /etc/kubernetes/pki/ca.crt
